name: mediatr
description: Dart mediatr package. Central mediator that allows sending requests, and publishing events.
version: 0.2.1
homepage: https://github.com/GeorgopoulosGiannis/dart_mediatr

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:

dev_dependencies:
  test: ^1.22.2
  lints: ^3.0.0
  mocktail: ^1.0.3

