name: mediatr
description: Dart mediatr package. Central mediator that allows sending requests, and publishing events.
version: 0.0.13
homepage: https://github.com/GeorgopoulosGiannis/dart_mediatr

environment:
  sdk: ">=2.17.5 <3.0.0"
  
dependencies:
  either_dart: ^0.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

